// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrtmNMC_xNpgTxnzRl33lWv2ZKmfFOITA',
    appId: '1:251871422990:web:77f5121f2eccd8f3ef2a5f',
    messagingSenderId: '251871422990',
    projectId: 'production-app-bf9be',
    authDomain: 'production-app-bf9be.firebaseapp.com',
    storageBucket: 'production-app-bf9be.appspot.com',
    measurementId: 'G-XYYKX78215',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE2WAK6T5nf8Y1n5yq0JKoattw741XA_Q',
    appId: '1:251871422990:android:122d6fb886dcb961ef2a5f',
    messagingSenderId: '251871422990',
    projectId: 'production-app-bf9be',
    storageBucket: 'production-app-bf9be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4gSQDWqJIM8BegPNr5E1M2BHm_urGo58',
    appId: '1:251871422990:ios:d42fb17107b99111ef2a5f',
    messagingSenderId: '251871422990',
    projectId: 'production-app-bf9be',
    storageBucket: 'production-app-bf9be.appspot.com',
    iosBundleId: 'com.example.productionapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4gSQDWqJIM8BegPNr5E1M2BHm_urGo58',
    appId: '1:251871422990:ios:d42fb17107b99111ef2a5f',
    messagingSenderId: '251871422990',
    projectId: 'production-app-bf9be',
    storageBucket: 'production-app-bf9be.appspot.com',
    iosBundleId: 'com.example.productionapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrtmNMC_xNpgTxnzRl33lWv2ZKmfFOITA',
    appId: '1:251871422990:web:7070c07270ce261aef2a5f',
    messagingSenderId: '251871422990',
    projectId: 'production-app-bf9be',
    authDomain: 'production-app-bf9be.firebaseapp.com',
    storageBucket: 'production-app-bf9be.appspot.com',
    measurementId: 'G-QQG6MYLS9H',
  );
}
